[package]
name = "instant-ico-meta"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.instant-ico]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.30.0"
